### ISSUE TITLE
Update with KSU manager don't work

### ISSUE THREAD

**Issue by MXC48** [mikropsoft/StevenBlock#6]
The download with the KerneSU app don't work in my android phone :/ It's normal ?

**Comment by mikropsoft** [comment]
> The download with the KerneSU app don't work in my android phone :/ It's normal ?

What do you mean by download?
If it's about the update, download the latest version from releases because I made some changes.

**Comment by mikropsoft** [comment]
Here it is now divided into 2 blocking lists. Download the one that suits you.

**Comment by MXC48** [comment]
Ok thanks, what is the difference between the two versions ?

**Comment by mikropsoft** [comment]
> Ok thanks, what is the difference between the two versions ?

Here is the English translation of your text:

---

These are two different hosts files. Normally, the StevenBlack block list has been used since the beginning of the repository, which is a more frequently updated list. Additionally, it has more entries than the 1hosts list. For those experiencing issues, I decided to add the 1hosts lite block list as an extra option. If you are only using it for ad blocking, frequent updates of the list won't be beneficial for you, so you might prefer 1hosts.

**Comment by mikropsoft** [comment]
> Ok thanks, what is the difference between the two versions ?

These are two different hosts files. Normally, the StevenBlack block list has been used since the beginning of the repository, which is a more frequently updated list. Additionally, it has more entries than the 1hosts list. For those experiencing issues, I decided to add the 1hosts lite block list as an extra option. If you are only using it for ad blocking, frequent updates of the list won't be beneficial for you, so you might prefer 1hosts.
